version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/website
    working_dir: /workspaces/website
    environment:
      QUARTO_PYTHON: /usr/local/bin/python3
    command: sleep infinity